//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSettings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class MensajesErrorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MensajesErrorSettings defaultInstance = ((MensajesErrorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MensajesErrorSettings())));
        
        public static MensajesErrorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ha habido un error al intentar conectar con la base de datos:")]
        public string MENSAJESERROR_TITULO_ERRORENBASEDEDATOS {
            get {
                return ((string)(this["MENSAJESERROR_TITULO_ERRORENBASEDEDATOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se pudo conectar con la base de datos. El tiempo de espera para la conexión su" +
            "peró el límite.")]
        public string MENSAJESERROR_CUERPO_BD_TIMEOUT {
            get {
                return ((string)(this["MENSAJESERROR_CUERPO_BD_TIMEOUT"]));
            }
        }
    }
}
